# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAL54uQXWug4lO7AF95z4QCj_ebYcohluWqWYGmfb";
    path = fetchzip {
      url = "https://storage.googleapis.com/flutter_infra_release/flutter/42d3d75a56efe1a2e9902f52dc8006099c45d937/linux-x64/linux-x64-embedder.zip";
      hash = "sha256-p42TKkhHZ96FR/6pvoGGaYtqidxl4GhdhjqQuBChLYc=";
    };
  }
  {
    name = "N-V-__8AAMCWEADA0AS-1LfBEtixZLJAb_XQKQpgSmR2uxAO";
    path = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland-protocols";
      rev = "02e63e74a807afed95bc25a386173110afef24e3";
      hash = "sha256-nleROoMciq1WassaZ+1ol6VxLWY5UwYlZC5+zNexFn8=";
    };
  }
  {
    name = "N-V-__8AAMq4AQASESNUzI38keQUB1Pz9OXa_YoUwXAgWQQl";
    path = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlr-protocols";
      rev = "bf4fc79abc359eea5a0edec0ac6d4a2b2955f82a";
      hash = "sha256-1G3RmqZFgPYnhCPOPFzXPnfloKn1/4IZ+VdOL6ppI/M=";
    };
  }
  {
    name = "wayland-0.6.0-dev-lQa1krD8AQBlMqwuhAMJjPQKXvpRByZBxxqMVAZ7yzbG";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-wayland";
      rev = "4a150a04f76f7329e80280661355c04328369d1f";
      hash = "sha256-B5nA05xYm6iRDDRFC2KUbhBCtjwmApka+BcDCZRssfw=";
    };
  }
  {
    name = "xkbcommon-0.5.0-dev-VDqIe0y2AgA1RzA2ICMdGhaAgSXdhtRTbYybQQu7WfOa";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-xkbcommon";
      rev = "6c2f41e269adde0d2cd58d20c02c4f8803d83eb1";
      hash = "sha256-vreObBYsAsb33qKdTpQGFqPbweidMw+L1MRWxqwq07E=";
    };
  }
]
