name: fushell
description: Dart API for the fushell player (surface roles, windows, and more).
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dbus: ^0.7.15
  flutter:
    sdk: flutter

dev_dependencies:
  xml: ">=6.6.1 <8.0.0"
  flutter_test:
    sdk: flutter
