name: icon_preview
description: Freedesktop icon lookup and Flutter rendering preview.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  fushell:
    path: ../../packages/fushell

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
